### ISSUE TITLE
Feature Request: Scaling a Row

### ISSUE THREAD

**Issue by agmath** [jonathanforhan/Row-Reducer-MAT-350#1]
Currently, it isn't intuitive to scale a row -- I can scale row 1 by replacing that row with 2*(row 1) + 1*(row_1), but not 3*(row_1) + 0*(row_2). I think a "fix" would be relatively easy to implement and would add to usability. 

**Possible Solution:** It seems like the applet currently checks to ensure that both scalars attached to rows are non-zero. If at least one scalar is zero, then an error message for "invalid input" is presented. If you change the check to ensure that at least one of the scalars is non-zero, then row scaling becomes more intuitive.

**Comment by jonathanforhan** [comment]
love the feedback! fixed in commit #825fb4a
