### ISSUE TITLE
New Feature Request: Auto Evaluation

### ISSUE THREAD

**Issue by gigoiy** [jonathanforhan/Row-Reducer-MAT-350#5]
A new feature that implements auto evaluation would be cool. I can implement if you want.

### To-Do's

**Completed**
- Added framework of `AutoEvaluation` class
- Added the `Auto Evaluate` tab in `index.html`
- Added `evaluate` function to `main.ts` 

**In-Progress**
- [ ] Add the guts to `evaluate` function
- [ ] Display the operation performed afterwards under the new `Auto Evaluate` tab in the GUI

**Comment by jonathanforhan** [comment]
This is a tool for students and faculty to show the process of Row Reducing, having an automatic evaluator is not the goal of this web app and will not be added as a feature now or in the future. I have educators that are already using this and counting on the functionality present so I need to be picky about the features and quality of prs I merge. I appreciate the interest in the project but there is no plan to implement this feature. Thanks!
